#!/bin/sh

BUILDDATE=`date +%Y%m%d%H%M%S`
# sudo MKSQUASHFS_OPTIONS="-b 1024k" lh_build 2>&1 | tee debian_live-binary-${BUILDDATE}.buildlog
lh_build noautoconfig 2>&1 | tee debian_live-binary-${BUILDDATE}.buildlog
#mv binary.img debian_live-binary-${BUILDDATE}.img
#[ -f binary.list] && mv binary.list debian_live-binary-${BUILDDATE}.list
#[ -f binary.packages ] && mv binary.packages debian_live-binary-${BUILDDATE}.packages
#md5sum debian_live-binary-${BUILDDATE}.img > debian_live-binary-${BUILDDATE}.img.md5sum

