#!/bin/sh

MIRROR_DEBIAN="http://ftp.jp.debian.org/debian/"
MIRROR_SECURITY="http://security.debian.org/"

lh_config noautoconfig \
	--apt-recommends disabled \
	--apt-secure disabled \
	--iso-publisher "Jun NOGATA; http://www.nofuture.tv/;" \
	--mirror-binary ${MIRROR_DEBIAN} \
	--mirror-binary-security ${MIRROR_SECURITY} \
	--mirror-bootstrap ${MIRROR_DEBIAN} \
	--mirror-chroot ${MIRROR_DEBIAN} \
	--mirror-chroot-security ${MIRROR_SECURITY} \
	--syslinux-timeout 30 \
	-l ja \
	${@}
