#!/bin/sh

MIRROR_DEBIAN="http://ftp.jp.debian.org/debian/"
MIRROR_SECURITY="http://security.debian.org/"

BOOTOPTION_LIVE="locale=ja_JP.UTF-8 keyb=jp kmodel=jp106 timezone=Asia/Tokyo vga=788 quiet"

lh_config noautoconfig \
	--binary-images usb-hdd \
	--binary-filesystem fat32 \
	--bootappend-live "${BOOTOPTION_LIVE}" \
	--apt-recommends disabled \
	--debian-installer live \
	--debian-installer-distribution lenny \
	--categories "main contrib non-free" \
	--distribution lenny \
	--linux-flavours 686 \
	--mirror-bootstrap ${MIRROR_DEBIAN} \
	--mirror-chroot ${MIRROR_DEBIAN} \
	--mirror-chroot-security ${MIRROR_SECURITY} \
	--mirror-binary ${MIRROR_DEBIAN} \
	--mirror-binary-security ${MIRROR_SECURITY} \
	-l ja \
	--linux-packages "linux-image-2.6.29-backports.1 aufs-modules-2.6.29-backports.1" \
	--packages-lists "lxde japanese kernel-modules packages rescuetools sustem" \
	--packages "bootchart bootchart-view lxlauncher" \
	--keyring-packages "debian-archive-keyring debian-backports-keyring" \
	--apt-secure disabled \
	${@}
